name = "faker"
type = "javascript"
main = "build/index.js"

account_id = "bfa8e5490905d68f7d555f04a6ab737d"
route = "faker"
workers_dev = true

[site]
bucket = "./public"

[build]
command = "npm run build"

[build.upload]
format="service-worker"
